# Generated by Django 3.2 on 2024-02-24 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('eventid', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=10)),
                ('eventtype', models.CharField(max_length=10)),
                ('eventtitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueid', models.IntegerField(blank=True)),
                ('timedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('matinee', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('ticket1', models.CharField(blank=True, max_length=100)),
                ('sheet1', models.CharField(blank=True, max_length=100)),
                ('floor1', models.CharField(blank=True, max_length=100)),
                ('block1', models.CharField(blank=True, max_length=100)),
                ('number1', models.CharField(blank=True, max_length=100)),
                ('ticket2', models.CharField(blank=True, max_length=100)),
                ('sheet2', models.CharField(blank=True, max_length=100)),
                ('floor2', models.CharField(blank=True, max_length=100)),
                ('block2', models.CharField(blank=True, max_length=100)),
                ('number2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VenueModel',
            fields=[
                ('venueid', models.IntegerField(primary_key=True, serialize=False)),
                ('venuedate', models.DateField()),
                ('prefecture', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsapp.eventmodel')),
            ],
        ),
    ]
