# Generated by Django 4.2.13 on 2024-06-02 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('eventid', models.IntegerField(primary_key=True, serialize=False)),
                ('eventtitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventTypeModel',
            fields=[
                ('eventtypeid', models.IntegerField(primary_key=True, serialize=False)),
                ('eventtype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HallInfoModel',
            fields=[
                ('hallid', models.IntegerField(primary_key=True, serialize=False)),
                ('hallname', models.CharField(max_length=100)),
                ('hallprefecture', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HallTypeDtlModel',
            fields=[
                ('typeid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='m_PerformTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp_priority', models.IntegerField()),
                ('perform_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SheetValMaster',
            fields=[
                ('valid', models.IntegerField(primary_key=True, serialize=False)),
                ('valname', models.CharField(max_length=100)),
                ('pattern', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketSheetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('sheet', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TicketTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('tickettype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VenueModel',
            fields=[
                ('venueid', models.IntegerField(primary_key=True, serialize=False)),
                ('venuedate', models.DateField()),
                ('rowmax', models.IntegerField(blank=True, default=1)),
                ('columnmax', models.IntegerField(blank=True, default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsapp.eventmodel')),
                ('hallinfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jsapp.hallinfomodel')),
                ('perform_time', models.ManyToManyField(default='', to='jsapp.m_performtime')),
                ('sheettype', models.ManyToManyField(default='', to='jsapp.ticketsheetmaster')),
                ('tickettype', models.ManyToManyField(default='', to='jsapp.tickettypemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SheetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('sheetname', models.CharField(max_length=100)),
                ('prename', models.CharField(blank=True, max_length=10)),
                ('postname', models.CharField(blank=True, max_length=10)),
                ('sheettype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsapp.sheetvalmaster')),
            ],
        ),
        migrations.CreateModel(
            name='MenberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerid', models.BigIntegerField(blank=True, default=1)),
                ('timedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('matinee', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('ticket1', models.CharField(blank=True, max_length=100)),
                ('sheet1', models.CharField(blank=True, max_length=100)),
                ('floor1', models.CharField(blank=True, max_length=100)),
                ('row1', models.CharField(blank=True, max_length=100)),
                ('block_r1', models.CharField(blank=True, max_length=100)),
                ('block_c1', models.CharField(blank=True, max_length=100)),
                ('number1', models.CharField(blank=True, max_length=100)),
                ('ticket2', models.CharField(blank=True, max_length=100)),
                ('sheet2', models.CharField(blank=True, max_length=100)),
                ('floor2', models.CharField(blank=True, max_length=100)),
                ('row2', models.CharField(blank=True, max_length=100)),
                ('block_r2', models.CharField(blank=True, max_length=100)),
                ('block_c2', models.CharField(blank=True, max_length=100)),
                ('number2', models.CharField(blank=True, max_length=100)),
                ('venueid', models.ForeignKey(blank=True, default=20240301, on_delete=django.db.models.deletion.CASCADE, to='jsapp.venuemodel')),
            ],
        ),
        migrations.CreateModel(
            name='HallTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('identname', models.CharField(max_length=100)),
                ('blockname', models.CharField(max_length=100)),
                ('hallval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsapp.halltypedtlmodel')),
                ('sheets', models.ManyToManyField(default=[1], to='jsapp.sheetmodel')),
            ],
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='eventtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsapp.eventtypemodel'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='group',
            field=models.ManyToManyField(default=[1], to='jsapp.groupmodel'),
        ),
    ]
