# Generated by Django 3.2 on 2024-02-02 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menbermodel',
            old_name='name',
            new_name='level1',
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='block1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='block2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='level2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='number1',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='number2',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='ptime',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='purchace1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='purchace2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='seatval1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='seatval2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='updatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
