# Generated by Django 4.2.13 on 2024-06-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='halltype',
            field=models.ManyToManyField(default='', to='jsapp.halltypemodel'),
        ),
    ]
