# Generated by Django 3.2 on 2024-02-02 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0002_auto_20240202_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menbermodel',
            name='level1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='level2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='number1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='number2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='purchace1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='purchace2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='seatval1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='seatval2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='updatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
