# Generated by Django 3.2 on 2024-02-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0003_auto_20240202_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menbermodel',
            name='block1',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='block2',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='level1',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='level2',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='number1',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='number2',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='purchace2',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='seatval1',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='seatval2',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='updatetime',
        ),
    ]
