# Generated by Django 3.2 on 2024-02-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0004_auto_20240202_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menbermodel',
            name='ptime',
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='night',
            field=models.BooleanField(default=False),
        ),
    ]
