# Generated by Django 3.2 on 2024-02-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0005_auto_20240202_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menbermodel',
            old_name='purchace1',
            new_name='block1',
        ),
        migrations.RenameField(
            model_name='menbermodel',
            old_name='day',
            new_name='evening',
        ),
        migrations.RenameField(
            model_name='menbermodel',
            old_name='night',
            new_name='matinee',
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='floor1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='number1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='sheet1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='ticket1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
