# Generated by Django 3.2 on 2024-02-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0007_alter_menbermodel_matinee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menbermodel',
            name='matinee',
            field=models.BooleanField(default=False),
        ),
    ]
