# Generated by Django 3.2 on 2024-02-11 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0008_alter_menbermodel_matinee'),
    ]

    operations = [
        migrations.AddField(
            model_name='menbermodel',
            name='block2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='floor2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='number2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='sheet2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='ticket2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='venue',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
