# Generated by Django 3.2 on 2024-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0009_auto_20240211_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='menbermodel',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
