# Generated by Django 3.2 on 2024-02-11 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0010_auto_20240211_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menbermodel',
            name='time',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='venue',
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='sheet1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='ticket1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
