# Generated by Django 3.2 on 2024-02-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0012_auto_20240211_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menbermodel',
            name='block1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='block2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='floor1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='floor2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='number1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='number2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='sheet1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='sheet2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='ticket1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='ticket2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
