# Generated by Django 3.2 on 2024-02-11 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0013_auto_20240211_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menbermodel',
            name='block2',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='floor2',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='number2',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='sheet2',
        ),
        migrations.RemoveField(
            model_name='menbermodel',
            name='ticket2',
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='block1',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='floor1',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='number1',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='sheet1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menbermodel',
            name='ticket1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
