# Generated by Django 3.2 on 2024-02-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0014_auto_20240211_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='menbermodel',
            name='block2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='floor2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='number2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='sheet2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='ticket2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
