# Generated by Django 3.2 on 2024-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0015_auto_20240211_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='menbermodel',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menbermodel',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
